services:
  web:
    image: ikhsan123/pjtrans:latest
    container_name: pjtrans
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
      - next-cache:/app/.next/cache
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pjtrans
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asintel123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:
  next-cache:

networks:
  app-network:
    driver: bridge
