services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/mydb?schema=public}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-changeme-please}
    volumes:
      - ./public/uploads:/app/public/uploads    # <— penting: map ke public/uploads
      - next-cache:/app/.next/cache             # (opsional) cache next/image
    # command: ["node", "server.js"]

volumes:
  next-cache:
